import { User, UserStatus } from '../types';

export const users: User[] = [
  {
    id: 1,
    name: 'Teppo',
    age: 25,
    status: UserStatus.BUSY,
    groupsList: ['car club'],
    avatar: undefined,
    verified: true,
  },
  {
    id: 2,
    name: 'Jari',
    age: 13,
    status: UserStatus.OFFLINE,
    groupsList: ['sewing club'],
    avatar: 'nice.jpg',
    verified: false,
  },
  {
    id: 3,
    name: 'Teppo',
    age: 25,
    status: UserStatus.BUSY,
    groupsList: ['car club'],
    avatar: undefined,
    verified: true,
  },
  {
    id: 4,
    name: 'Jari',
    age: 13,
    status: UserStatus.OFFLINE,
    groupsList: ['sewing club'],
    avatar: 'nice.jpg',
    verified: false,
  },
  {
    id: 5,
    name: 'Teppo',
    age: 25,
    status: UserStatus.BUSY,
    groupsList: ['car club'],
    avatar: undefined,
    verified: true,
  },
  {
    id: 6,
    name: 'Jari',
    age: 13,
    status: UserStatus.OFFLINE,
    groupsList: ['sewing club'],
    avatar: 'nice.jpg',
    verified: false,
  },
  {
    id: 7,
    name: 'Teppo',
    age: 25,
    status: UserStatus.BUSY,
    groupsList: ['car club'],
    avatar: undefined,
    verified: true,
  },
  {
    id: 8,
    name: 'Jari',
    age: 13,
    status: UserStatus.OFFLINE,
    groupsList: ['sewing club'],
    avatar: 'nice.jpg',
    verified: false,
  },
  {
    id: 9,
    name: 'Teppo',
    age: 25,
    status: UserStatus.AVAILABLE,
    groupsList: ['car club'],
    avatar: undefined,
    verified: true,
  },
  {
    id: 10,
    name: 'Jari',
    age: 13,
    status: UserStatus.OFFLINE,
    groupsList: ['sewing club'],
    avatar: 'nice.jpg',
    verified: false,
  },
  {
    id: 11,
    name: 'Teppo',
    age: 25,
    status: UserStatus.BUSY,
    groupsList: ['car club'],
    avatar: undefined,
    verified: true,
  },
  {
    id: 12,
    name: 'Jari',
    age: 13,
    status: UserStatus.OFFLINE,
    groupsList: ['sewing club'],
    avatar: 'nice.jpg',
    verified: false,
  },
  {
    id: 13,
    name: 'Teppo',
    age: 25,
    status: UserStatus.BUSY,
    groupsList: ['car club'],
    avatar: undefined,
    verified: true,
  },
  {
    id: 14,
    name: 'Jari',
    age: 13,
    status: UserStatus.OFFLINE,
    groupsList: ['sewing club'],
    avatar: 'nice.jpg',
    verified: false,
  },
  {
    id: 15,
    name: 'Teppo',
    age: 25,
    status: UserStatus.BUSY,
    groupsList: ['car club'],
    avatar: undefined,
    verified: true,
  },
  {
    id: 16,
    name: 'Jari',
    age: 13,
    status: UserStatus.OFFLINE,
    groupsList: ['sewing club'],
    avatar: 'nice.jpg',
    verified: false,
  },
  {
    id: 17,
    name: 'Teppo',
    age: 25,
    status: UserStatus.BUSY,
    groupsList: ['car club'],
    avatar: undefined,
    verified: true,
  },
  {
    id: 18,
    name: 'Jari',
    age: 13,
    status: UserStatus.OFFLINE,
    groupsList: ['sewing club'],
    avatar: 'nice.jpg',
    verified: false,
  },
  {
    id: 19,
    name: 'Teppo',
    age: 25,
    status: UserStatus.AVAILABLE,
    groupsList: ['car club'],
    avatar: undefined,
    verified: true,
  },
  {
    id: 20,
    name: 'Jari',
    age: 13,
    status: UserStatus.OFFLINE,
    groupsList: ['sewing club'],
    avatar: 'nice.jpg',
    verified: false,
  },
  {
    id: 21,
    name: 'Teppo',
    age: 25,
    status: UserStatus.BUSY,
    groupsList: ['car club'],
    avatar: undefined,
    verified: true,
  },
  {
    id: 22,
    name: 'Jari',
    age: 13,
    status: UserStatus.OFFLINE,
    groupsList: ['sewing club'],
    avatar: 'nice.jpg',
    verified: false,
  },
  {
    id: 23,
    name: 'Teppo',
    age: 25,
    status: UserStatus.BUSY,
    groupsList: ['car club'],
    avatar: undefined,
    verified: true,
  },
  {
    id: 24,
    name: 'Jari',
    age: 13,
    status: UserStatus.OFFLINE,
    groupsList: ['sewing club'],
    avatar: 'nice.jpg',
    verified: false,
  },
  {
    id: 25,
    name: 'Teppo',
    age: 25,
    status: UserStatus.BUSY,
    groupsList: ['car club'],
    avatar: undefined,
    verified: true,
  },
  {
    id: 26,
    name: 'Jari',
    age: 13,
    status: UserStatus.OFFLINE,
    groupsList: ['sewing club'],
    avatar: 'nice.jpg',
    verified: false,
  },
  {
    id: 27,
    name: 'Teppo',
    age: 25,
    status: UserStatus.BUSY,
    groupsList: ['car club'],
    avatar: undefined,
    verified: true,
  },
  {
    id: 28,
    name: 'Jari',
    age: 13,
    status: UserStatus.OFFLINE,
    groupsList: ['sewing club'],
    avatar: 'nice.jpg',
    verified: false,
  },
  {
    id: 29,
    name: 'Teppo',
    age: 25,
    status: UserStatus.AVAILABLE,
    groupsList: ['car club'],
    avatar: undefined,
    verified: true,
  },
  {
    id: 30,
    name: 'Jari',
    age: 13,
    status: UserStatus.OFFLINE,
    groupsList: ['sewing club'],
    avatar: 'nice.jpg',
    verified: false,
  },
  {
    id: 31,
    name: 'Teppo',
    age: 25,
    status: UserStatus.BUSY,
    groupsList: ['car club'],
    avatar: undefined,
    verified: true,
  },
  {
    id: 32,
    name: 'Jari',
    age: 13,
    status: UserStatus.OFFLINE,
    groupsList: ['sewing club'],
    avatar: 'nice.jpg',
    verified: false,
  },
  {
    id: 33,
    name: 'Teppo',
    age: 25,
    status: UserStatus.BUSY,
    groupsList: ['car club'],
    avatar: undefined,
    verified: true,
  },
  {
    id: 34,
    name: 'Jari',
    age: 13,
    status: UserStatus.OFFLINE,
    groupsList: ['sewing club'],
    avatar: 'nice.jpg',
    verified: false,
  },
  {
    id: 35,
    name: 'Teppo',
    age: 25,
    status: UserStatus.BUSY,
    groupsList: ['car club'],
    avatar: undefined,
    verified: true,
  },
  {
    id: 36,
    name: 'Jari',
    age: 13,
    status: UserStatus.OFFLINE,
    groupsList: ['sewing club'],
    avatar: 'nice.jpg',
    verified: false,
  },
  {
    id: 37,
    name: 'Teppo',
    age: 25,
    status: UserStatus.BUSY,
    groupsList: ['car club'],
    avatar: undefined,
    verified: true,
  },
  {
    id: 38,
    name: 'Jari',
    age: 13,
    status: UserStatus.OFFLINE,
    groupsList: ['sewing club'],
    avatar: 'nice.jpg',
    verified: false,
  },

  {
    id: 39,
    name: 'Jari',
    age: 13,
    status: UserStatus.UNKNOWN,
    groupsList: ['sewing club'],
    avatar: 'nice.jpg',
    verified: false,
  },
  {
    id: 40,
    name: 'Jari',
    age: 13,
    status: UserStatus.OFFLINE,
    groupsList: ['sewing club'],
    avatar: 'nice.jpg',
    verified: false,
  },
  {
    id: 41,
    name: 'Teppo',
    age: 25,
    status: UserStatus.BUSY,
    groupsList: ['car club'],
    avatar: undefined,
    verified: true,
  },
  {
    id: 42,
    name: 'Jari',
    age: 13,
    status: UserStatus.OFFLINE,
    groupsList: ['sewing club'],
    avatar: 'nice.jpg',
    verified: false,
  },
  {
    id: 43,
    name: 'Teppo',
    age: 25,
    status: UserStatus.BUSY,
    groupsList: ['car club'],
    avatar: undefined,
    verified: true,
  },
  {
    id: 44,
    name: 'Jari',
    age: 13,
    status: UserStatus.OFFLINE,
    groupsList: ['sewing club'],
    avatar: 'nice.jpg',
    verified: false,
  },
  {
    id: 45,
    name: 'Teppo',
    age: 25,
    status: UserStatus.BUSY,
    groupsList: ['car club'],
    avatar: undefined,
    verified: true,
  },
  {
    id: 46,
    name: 'Jari',
    age: 13,
    status: UserStatus.OFFLINE,
    groupsList: ['sewing club'],
    avatar: 'nice.jpg',
    verified: false,
  },
  {
    id: 47,
    name: 'Teppo',
    age: 25,
    status: UserStatus.BUSY,
    groupsList: ['car club'],
    avatar: undefined,
    verified: true,
  },
  {
    id: 48,
    name: 'Jari',
    age: 13,
    status: UserStatus.OFFLINE,
    groupsList: ['sewing club'],
    avatar: 'nice.jpg',
    verified: false,
  },
  {
    id: 49,
    name: 'Teppo',
    age: 25,
    status: UserStatus.AVAILABLE,
    groupsList: ['car club'],
    avatar: undefined,
    verified: true,
  },
  {
    id: 50,
    name: 'Jari',
    age: 13,
    status: UserStatus.UNKNOWN,
    groupsList: ['sewing club'],
    avatar: 'nice.jpg',
    verified: false,
  },
];
